version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: watermill-coordinator
    main: ./cmd/coordinator
    binary: coordinator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

sboms:
  - id: archive-sboms
    artifacts: archive

signs:
  - id: checksum-signature
    cmd: cosign
    signature: "${artifact}.bundle"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: "Features"
      regexp: '^.*feat[(\w\s)]*:'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*fix[(\w\s)]*:'
      order: 1
    - title: "Security Updates"
      regexp: '^.*sec[(\w\s)]*:'
      order: 2
    - title: "Others"
      order: 999
