// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: coordinator.proto

package coordinatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishResponse_Status int32

const (
	PublishResponse_STATUS_UNSPECIFIED PublishResponse_Status = 0
	PublishResponse_PUBLISHED          PublishResponse_Status = 1
	PublishResponse_ALREADY_EXISTS     PublishResponse_Status = 2 // Idempotent duplicate
)

// Enum value maps for PublishResponse_Status.
var (
	PublishResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "PUBLISHED",
		2: "ALREADY_EXISTS",
	}
	PublishResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PUBLISHED":          1,
		"ALREADY_EXISTS":     2,
	}
)

func (x PublishResponse_Status) Enum() *PublishResponse_Status {
	p := new(PublishResponse_Status)
	*p = x
	return p
}

func (x PublishResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_proto_enumTypes[0].Descriptor()
}

func (PublishResponse_Status) Type() protoreflect.EnumType {
	return &file_coordinator_proto_enumTypes[0]
}

func (x PublishResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishResponse_Status.Descriptor instead.
func (PublishResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_coordinator_proto_enumTypes[1]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{8, 0}
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Event         *CloudEvent            `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetEvent() *CloudEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PublishResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=coordinator.PublishResponse_Status" json:"status,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetStatus() PublishResponse_Status {
	if x != nil {
		return x.Status
	}
	return PublishResponse_STATUS_UNSPECIFIED
}

func (x *PublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PublishResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SubscribeClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*SubscribeClientMessage_Start
	//	*SubscribeClientMessage_Ack
	//	*SubscribeClientMessage_Nack
	Action        isSubscribeClientMessage_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeClientMessage) Reset() {
	*x = SubscribeClientMessage{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeClientMessage) ProtoMessage() {}

func (x *SubscribeClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeClientMessage.ProtoReflect.Descriptor instead.
func (*SubscribeClientMessage) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeClientMessage) GetAction() isSubscribeClientMessage_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *SubscribeClientMessage) GetStart() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Action.(*SubscribeClientMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *SubscribeClientMessage) GetAck() *AckRequest {
	if x != nil {
		if x, ok := x.Action.(*SubscribeClientMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *SubscribeClientMessage) GetNack() *NackRequest {
	if x != nil {
		if x, ok := x.Action.(*SubscribeClientMessage_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

type isSubscribeClientMessage_Action interface {
	isSubscribeClientMessage_Action()
}

type SubscribeClientMessage_Start struct {
	Start *SubscribeRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type SubscribeClientMessage_Ack struct {
	Ack *AckRequest `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type SubscribeClientMessage_Nack struct {
	Nack *NackRequest `protobuf:"bytes,3,opt,name=nack,proto3,oneof"`
}

func (*SubscribeClientMessage_Start) isSubscribeClientMessage_Action() {}

func (*SubscribeClientMessage_Ack) isSubscribeClientMessage_Action() {}

func (*SubscribeClientMessage_Nack) isSubscribeClientMessage_Action() {}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *NackRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *NackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Event         *CloudEvent            `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *EventMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventMessage) GetEvent() *CloudEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=coordinator.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\vcoordinator\x1a\x11cloudevents.proto\"[\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x123\n" +
	"\x05event\x18\x02 \x01(\v2\x1d.io.cloudevents.v1.CloudEventR\x05event\"\xe6\x01\n" +
	"\x0fPublishResponse\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.coordinator.PublishResponse.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"C\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x02\"\xb6\x01\n" +
	"\x16SubscribeClientMessage\x125\n" +
	"\x05start\x18\x01 \x01(\v2\x1d.coordinator.SubscribeRequestH\x00R\x05start\x12+\n" +
	"\x03ack\x18\x02 \x01(\v2\x17.coordinator.AckRequestH\x00R\x03ack\x12.\n" +
	"\x04nack\x18\x03 \x01(\v2\x18.coordinator.NackRequestH\x00R\x04nackB\b\n" +
	"\x06action\"O\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\"+\n" +
	"\n" +
	"AckRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"D\n" +
	"\vNackRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Y\n" +
	"\fEventMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x123\n" +
	"\x05event\x18\x02 \x01(\v2\x1d.io.cloudevents.v1.CloudEventR\x05event\"\x14\n" +
	"\x12HealthCheckRequest\"\x99\x01\n" +
	"\x13HealthCheckResponse\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..coordinator.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xfd\x01\n" +
	"\x12CoordinatorService\x12D\n" +
	"\aPublish\x12\x1b.coordinator.PublishRequest\x1a\x1c.coordinator.PublishResponse\x12O\n" +
	"\tSubscribe\x12#.coordinator.SubscribeClientMessage\x1a\x19.coordinator.EventMessage(\x010\x01\x12P\n" +
	"\vCheckHealth\x12\x1f.coordinator.HealthCheckRequest\x1a .coordinator.HealthCheckResponseBr\n" +
	"\x1eio.watermill.coordinator.protoB\x10CoordinatorProtoP\x01Z<github.com/magnusp/watermill-coordinator/proto;coordinatorpbb\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_coordinator_proto_goTypes = []any{
	(PublishResponse_Status)(0),            // 0: coordinator.PublishResponse.Status
	(HealthCheckResponse_ServingStatus)(0), // 1: coordinator.HealthCheckResponse.ServingStatus
	(*PublishRequest)(nil),                 // 2: coordinator.PublishRequest
	(*PublishResponse)(nil),                // 3: coordinator.PublishResponse
	(*SubscribeClientMessage)(nil),         // 4: coordinator.SubscribeClientMessage
	(*SubscribeRequest)(nil),               // 5: coordinator.SubscribeRequest
	(*AckRequest)(nil),                     // 6: coordinator.AckRequest
	(*NackRequest)(nil),                    // 7: coordinator.NackRequest
	(*EventMessage)(nil),                   // 8: coordinator.EventMessage
	(*HealthCheckRequest)(nil),             // 9: coordinator.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 10: coordinator.HealthCheckResponse
	(*CloudEvent)(nil),                     // 11: io.cloudevents.v1.CloudEvent
}
var file_coordinator_proto_depIdxs = []int32{
	11, // 0: coordinator.PublishRequest.event:type_name -> io.cloudevents.v1.CloudEvent
	0,  // 1: coordinator.PublishResponse.status:type_name -> coordinator.PublishResponse.Status
	5,  // 2: coordinator.SubscribeClientMessage.start:type_name -> coordinator.SubscribeRequest
	6,  // 3: coordinator.SubscribeClientMessage.ack:type_name -> coordinator.AckRequest
	7,  // 4: coordinator.SubscribeClientMessage.nack:type_name -> coordinator.NackRequest
	11, // 5: coordinator.EventMessage.event:type_name -> io.cloudevents.v1.CloudEvent
	1,  // 6: coordinator.HealthCheckResponse.status:type_name -> coordinator.HealthCheckResponse.ServingStatus
	2,  // 7: coordinator.CoordinatorService.Publish:input_type -> coordinator.PublishRequest
	4,  // 8: coordinator.CoordinatorService.Subscribe:input_type -> coordinator.SubscribeClientMessage
	9,  // 9: coordinator.CoordinatorService.CheckHealth:input_type -> coordinator.HealthCheckRequest
	3,  // 10: coordinator.CoordinatorService.Publish:output_type -> coordinator.PublishResponse
	8,  // 11: coordinator.CoordinatorService.Subscribe:output_type -> coordinator.EventMessage
	10, // 12: coordinator.CoordinatorService.CheckHealth:output_type -> coordinator.HealthCheckResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	file_cloudevents_proto_init()
	file_coordinator_proto_msgTypes[2].OneofWrappers = []any{
		(*SubscribeClientMessage_Start)(nil),
		(*SubscribeClientMessage_Ack)(nil),
		(*SubscribeClientMessage_Nack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		EnumInfos:         file_coordinator_proto_enumTypes,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
